core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("products.urls"))
]

products/urls.py
from django.urls import path
from . import views

app_name = "products"

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.add, name="add"),
    path('<int:id>', views.each, name="each"),
    path('<int:id>/edit', views.edit, name="edit"),
    path('<int:id>/delete', views.delete, name="delete")
]

products/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=5, decimal_places=2)

products/views.py
from itertools import product
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from .form.form import ProductForm
# Create your views here.


def index(req):
    if req.method == "POST":
        form = ProductForm(req.POST)
        if form.is_valid():
            form.save()
            return redirect("products:index")
        return render(req, "products/add.html", {"form": form})
    products = Product.objects.order_by("-id")
    return render(req, "products/index.html", {"products": products})


def add(req):
    form = ProductForm()
    return render(req, "products/add.html", {"form": form})


def each(req, id):
    product = get_object_or_404(Product, id=id)
    if req.method == "POST":
        form = ProductForm(req.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect("products:each", id=id)
        return render(req, "products/edit.html", {"product": product, "form": form})
    return render(req, "products/each.html", {"product": product})


def edit(req, id):
    product = get_object_or_404(Product, id=id)
    form = ProductForm(instance=product)
    return render(req, "products/edit.html", {"product": product, "form": form})


def delete(req, id):
    product = get_object_or_404(Product, id=id)
    product.delete()
    return redirect("products:index")

products/templates/products/add.html
{% extends "layouts/base.html" %}

{% block content %}
<div>
    <form action="{% url "products:index" %}" method="POST">
        {% csrf_token %}

        {{form}}

        <button>add this new product</button>
    </form>
    <a href="{% url "products:index" %}">back to home page</a>
</div>
{% endblock %}

products/templates/products/each.html
{% extends "layouts/base.html" %}

{% block content %}
<div>
    <h1>{{product.title}}</h1>
    <article>{{product.description}}</article>
    <p>{{product.price}}</p>

    <div>
        <a href="{% url "products:edit" product.id%}">edit this product</a>
    </div>

    <div>
        <a onClick="return confirm('you sure you want to delete this product?')" href="{% url "products:delete" product.id%}">delete this product</a>
    </div>

    <a href="{% url "products:index" %}">back to home page</a>
</div>
{% endblock %}

products/templates/products/edit.html
{% extends "layouts/base.html" %}

{% block content %}
<div>
    <form action="{% url "products:each" product.id%}" method="POST">
        {% csrf_token %}

        {{form}}

        <button>save thid edit</button>
    </form>
    <a href="{% url "products:each" product.id%}">discard this edit</a>
</div>
{% endblock %}

products/templates/products/index.html
{% extends "layouts/base.html" %}

{% block content %}
<div>
    <h1>here are the products</h1>
    <ul>
        {% for product in products %}
            <a href="{% url "products:each" product.id%}">
                <li>
                    <h3>{{product.title}}</h3>
                    <p>{{product.description}}</p>
                    <p>{{product.price}}</p>
                </li>
            </a>
        {% endfor %}
    </ul>
    <a href="{% url "products:add" %}">add a new product</a>
</div>
{% endblock %}

templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>